/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.3.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "2026-lae-41d-42d"
include("lesson09-reflect-kotlin")
include("lesson10-reflect-java")
include("lesson12-domain-model")
// include("lesson12-naive-mapper")
include("lesson13-annotations")
include("lesson15-naive-mapper-via-constructor")
include("lesson15-reflect-callBy")
include("lesson18-naive-mapper-opt")
include("lesson18-JMH-microbench-mapper")
include("lesson22-class-file-api")
include("lesson24-dynamic-mapper")
