/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import buildFoo
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.*

class FooBuilderTest {
    @Test
    fun metaprogrammingTest() {
        val method = buildFoo()

        val a = 7
        val b = 0.03f
        val c = 3
        val d = 1.25f

        val generated = method.call(a, b, c, d)
        val expected = Foo(a, b, c, d)
        assertEquals(expected, generated)
    }
}
